import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
//import styles from '@/styles/Home.module.css'
import { TopNav } from '@/components/top-nav';
import { styled } from '@mui/material/styles';
import { Box } from '@mui/system';
import { Card, Grid, CardContent } from '@mui/material';
import Hero from '@/components/Hero';
import SVG from '../assets/trace.svg'
import Carousel from '@/components/Carousel';
const inter = Inter({ subsets: ['latin'] })


const SIDE_NAV_WIDTH = 280;
const LayoutRoot = styled('div')(() => ({
  display: 'flex',
  flex: '1 1 auto',
  maxWidth: '100%',
  marginTop:'0em'
/*   [theme.breakpoints.up('lg')]: {
    paddingLeft: SIDE_NAV_WIDTH
  } */
}));
const LayoutContainer = styled('div')({
   display: 'flex',
  flex: '1 1 auto',
  flexDirection: 'column',
  width: '100%' 
});




export default function Home() {

    const handleHover = (event) => {
      event.currentTarget.style.transform = 'scale(1.1)'; // Cambiar el tamaño al 110%
    };
  
    const handleLeave = (event) => {
      event.currentTarget.style.transform = 'scale(.5)'; // Volver al tamaño original
    };


  return (
    <>
      <Head>
        <title>Soluciones RP</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/icono.png" />
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
        <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@700&display=swap" rel="stylesheet"></link>
        <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@600&display=swap" rel="stylesheet"></link>
      </Head>

{/* <TopNav/> */}

      <LayoutRoot>
        <LayoutContainer>
        <main>

          
    <Image src={SVG} alt="Icon" width={115} height={115}  style={{ width:'100%', zIndex:9999, right:520, top:13, position:'fixed' }}  />
    <TopNav/>
    
    <Card elevation={0} sx={{height:130, width:200, backgroundColor: 'white', ml:15, p:2}} style={{  position: 'fixed', zIndex:7777}}>
    

          </Card>
        
<Hero/>


<Carousel />

<Box  height={300} style={{backgroundColor: 'red', position:'absolute',  marginTop:'0%'}}  ></Box>


</main> 
</LayoutContainer>
      </LayoutRoot>

  

    </>
  )
}
