import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
//import styles from '@/styles/Home.module.css'
import ResponsiveAppBar from '@/components/navbar'
import { Carrousel } from '@/components/carousel'
import Servicios from '@/components/servicios'
import { Contacto } from '@/components/contacto'
import { CardContact } from '@/components/CardContact'
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

<main>

   <ResponsiveAppBar/>
   <Carrousel/>
   <CardContact/>
   <Contacto/>
   <Servicios/>
   

</main>    

    </>
  )
}
